## Questão 2

#### Obs.: Inicialmente o código não funciona, após a sua implementação o mesmo deverá funcionar.

### Classe Problema

In [ ]:
import numpy as np

class SlidingPuzzle():
    def __init__(self, num_blocos):
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if estado[i, j] == elemento:
                    return i, j
        return None, None

    def verifica_estados(self, atual, objetivo):
        flag = True
        for i in range(self.num_blocos):
            if flag == False:
                break

            for j in range(self.num_blocos):
                if atual[i, j] != objetivo[i, j]:
                    flag = False;
                    break;

        return flag

    def expande_estado(self, atual):
        novos_estados = []
        linha, coluna = self._encontra_posicao(atual, 0)

        # Cima
        if linha > 0:
            novo_estado = np.copy(atual)
            nova_linha = linha - 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Baixo
        if linha < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_linha = linha + 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)


        # Esquerda
        if coluna > 0:
            novo_estado = np.copy(atual)
            nova_coluna = coluna - 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Direita
        if coluna < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_coluna = coluna + 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        return novos_estados

    def heuristica(self, atual, objetivo):
        heuristica = 0
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if atual[i, j] != objetivo[i, j]:
                    heuristica = +1
        return heuristica

### Busca Gulosa

In [ ]:
import heapq

class BuscaGulosa():
    def __init__(self, problema):
        self.problema = problema

    def _verifica_visitado(self, estado, estados_visitados):
        for i in estados_visitados:
            if self.problema.verifica_estados(i, estado):
                return True
        return False

    def busca(self, inicio, fim):
        p_fila = []
        
        # H, ID, elemento
        heapq.heappush(p_fila, (0, 0, inicio))

        id_estado = 0
        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0

        while not len(p_fila) == 0:
            atual = heapq.heappop(p_fila)[2]
            estados_visitados.append(atual)

            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
            else:
                cont_estados += 1
                print("Visitando #", cont_estados)
                novos_estados = self.problema.expande_estado(atual)

                for i in novos_estados:
                    if not self._verifica_visitado(i, estados_visitados):
                        id_estado += 1
                        prioridade = self.problema.heuristica(i, fim)

                        print(i, "\nh = ", prioridade)
                        heapq.heappush(p_fila, (prioridade, id_estado, i))

        return solucao_encontrada, estados_visitados, cont_estados


### Chamando a Busca

In [ ]:
problema = SlidingPuzzle(3)

start = np.matrix([[2, 8, 3], [1, 6, 4], [7, 5, 0]])
print(start, "\n********\n")

target = np.matrix([[1, 2, 3], [8, 0, 4], [7, 6, 5]])
print(target, "\n********\n")

gulosa = BuscaGulosa(problema)
solucao, visitados, steps = gulosa.busca(start, target)

if solucao:
    print(f"Solução encontrada em {steps} passos")
else:
    print("Solução não encontrada")

A saída de streaming foi truncada nas últimas 5000 linhas.
h =  1
[[1 8 4]
 [2 0 5]
 [3 7 6]] 
h =  1
Visitando # 4154
[[0 6 4]
 [3 7 2]
 [8 1 5]] 
h =  1
[[3 6 4]
 [7 0 2]
 [8 1 5]] 
h =  1
Visitando # 4155
[[3 6 0]
 [8 7 4]
 [1 5 2]] 
h =  1
[[3 6 4]
 [8 0 7]
 [1 5 2]] 
h =  1
Visitando # 4156
[[3 6 4]
 [1 0 2]
 [7 8 5]] 
h =  1
[[3 6 4]
 [1 8 2]
 [7 5 0]] 
h =  1
Visitando # 4157
[[3 6 4]
 [8 2 5]
 [0 1 7]] 
h =  1
Visitando # 4158
[[3 4 2]
 [8 0 5]
 [1 6 7]] 
h =  1
[[3 4 2]
 [8 6 5]
 [0 1 7]] 
h =  1
Visitando # 4159
[[0 3 2]
 [8 4 6]
 [1 7 5]] 
h =  1
[[3 2 0]
 [8 4 6]
 [1 7 5]] 
h =  1
Visitando # 4160
[[3 4 2]
 [8 7 6]
 [0 1 5]] 
h =  1
[[3 4 2]
 [8 7 6]
 [1 5 0]] 
h =  1
Visitando # 4161
[[0 4 2]
 [3 8 6]
 [1 7 5]] 
h =  1
[[3 4 2]
 [1 8 6]
 [0 7 5]] 
h =  1
Visitando # 4162
[[0 6 3]
 [8 5 4]
 [1 7 2]] 
h =  1
[[8 6 3]
 [5 0 4]
 [1 7 2]] 
h =  1
Visitando # 4163
[[8 6 0]
 [1 5 3]
 [7 2 4]] 
h =  1
[[8 6 3]
 [1 0 5]
 [7 2 4]] 
h =  1
Visitando # 4164
[[6 1 3]
 [8 0 4]
 [7 5 2]]